# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: XinYangBuXi

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  watch:
    types: started
  schedule:
    - cron: "0 0/4 * * *"

jobs:
  XinYangBuXi:
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2

    - name: 'setup python'
      uses: actions/setup-python@master
      with: 
        python-version: 3.7
      
    - name: requirements
      run: |
        pip3 install -r requirements.txt
        
    - name: Checkin
      run: |
        python daka.py
        
    - name: 'Avoid Github Workflow being suspended'
      run: echo $(cat /proc/sys/kernel/random/uuid) > UUID.txt
    
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am 'avoid being suspended'
        echo ::set-output name=status::success
           
    - name: 'GitHub Push'
      if: steps.commit.output.status != 'success'
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
